import os
import re
import secrets
import smtplib
from datetime import datetime, timedelta
from email.message import EmailMessage
from functools import wraps

from dotenv import load_dotenv
from flask import Flask, abort, flash, g, make_response, redirect, render_template, request, send_file, session, url_for
from flask_login import current_user, login_required
from sqlalchemy import text
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename

load_dotenv()


def get_database_uri():
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        return database_url.replace("postgres://", "postgresql://", 1)
    os.makedirs(os.path.join(os.path.dirname(__file__), "instance"), exist_ok=True)
    database_path = os.path.join(os.path.dirname(__file__), "instance", "platform.db")
    return "sqlite:///" + database_path


app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "change-this-secret-key")
app.config["DATABASE"] = os.environ.get("DATABASE_URL") or os.path.join(app.instance_path, "platform.db")
app.config["SQLALCHEMY_DATABASE_URI"] = get_database_uri()
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["UPLOAD_FOLDER"] = os.path.join(app.root_path, "static", "images")
app.config["CONTENT_UPLOAD_FOLDER"] = os.path.join(app.root_path, "static", "uploads", "content")
app.config["MAX_CONTENT_LENGTH"] = 500 * 1024 * 1024

from school_app.extensions import db, login_manager
from school_app.models import Admin, ContentItem, Course, CourseEnrollment, EssaySubmission, ExamQuestion, StudentExamReport, StudentForumQuestion
from school_app.admin_routes import admin_bp

db.init_app(app)
login_manager.init_app(app)
app.register_blueprint(admin_bp, url_prefix="/admin")


@login_manager.user_loader
def load_admin(admin_id):
    return db.session.get(Admin, int(admin_id))


def get_db():
    if app.config["SQLALCHEMY_DATABASE_URI"].startswith("sqlite"):
        import sqlite3
        if "db" not in g:
            os.makedirs(app.instance_path, exist_ok=True)
            g.db = sqlite3.connect(app.config["DATABASE"])
            g.db.row_factory = sqlite3.Row
        return g.db
    raise RuntimeError("Use db.session.execute(...) for PostgreSQL-backed database access.")


def init_db():
    dialect = db.engine.dialect.name
    inspector = db.inspect(db.engine)

    if "users" not in inspector.get_table_names():
        if dialect == "postgresql":
            db.session.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    phone TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    grade TEXT NOT NULL,
                    study_type TEXT NOT NULL,
                    password TEXT NOT NULL,
                    score INTEGER DEFAULT 0,
                    guardian_phone TEXT DEFAULT '',
                    reset_token TEXT DEFAULT '',
                    reset_token_expires_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """))
        else:
            db.session.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    phone TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    grade TEXT NOT NULL,
                    study_type TEXT NOT NULL,
                    password TEXT NOT NULL,
                    score INTEGER DEFAULT 0,
                    guardian_phone TEXT DEFAULT '',
                    reset_token TEXT DEFAULT '',
                    reset_token_expires_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """))
        db.session.commit()

    user_columns = {column["name"] for column in inspector.get_columns("users")}
    for column_name, definition in {
        "score": "INTEGER DEFAULT 0",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        "reset_token": "TEXT DEFAULT ''",
        "reset_token_expires_at": "TIMESTAMP",
        "guardian_phone": "TEXT DEFAULT ''",
    }.items():
        if column_name not in user_columns:
            db.session.execute(text(f"ALTER TABLE users ADD COLUMN {column_name} {definition}"))
    db.session.commit()

    for table_name, ddl in {
        "challenge_scores": """
            CREATE TABLE IF NOT EXISTS challenge_scores (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                score INTEGER NOT NULL DEFAULT 0,
                reason TEXT,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """,
        "student_exam_reports": """
            CREATE TABLE IF NOT EXISTS student_exam_reports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                course_id INTEGER NOT NULL,
                score INTEGER NOT NULL DEFAULT 0,
                total INTEGER NOT NULL DEFAULT 0,
                result_status VARCHAR(30) NOT NULL DEFAULT 'pending',
                review_summary TEXT DEFAULT '',
                achievements TEXT DEFAULT '',
                weak_points TEXT DEFAULT '',
                admin_analysis TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """,
        "essay_submissions": """
            CREATE TABLE IF NOT EXISTS essay_submissions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                course_id INTEGER NOT NULL,
                question_id INTEGER NOT NULL,
                answer TEXT DEFAULT '',
                score INTEGER NOT NULL DEFAULT 0,
                feedback TEXT DEFAULT '',
                status VARCHAR(30) NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """,
        "student_forum_questions": """
            CREATE TABLE IF NOT EXISTS student_forum_questions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                question TEXT NOT NULL,
                image TEXT DEFAULT '',
                answer TEXT DEFAULT '',
                answered_by TEXT DEFAULT '',
                answered_at TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """,
    }.items():
        if table_name not in inspector.get_table_names():
            if dialect == "postgresql" and table_name in {"challenge_scores", "student_exam_reports", "essay_submissions", "student_forum_questions"}:
                create_sql = ddl.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            else:
                create_sql = ddl
            db.session.execute(text(create_sql))
    db.session.commit()

    for table_name, extra_columns in {
        "student_exam_reports": {"result_status": "VARCHAR(30) DEFAULT 'pending'", "review_summary": "TEXT DEFAULT ''"},
        "essay_submissions": {"score": "INTEGER NOT NULL DEFAULT 0", "feedback": "TEXT DEFAULT ''", "status": "VARCHAR(30) DEFAULT 'pending'"},
        "student_forum_questions": {"question": "TEXT NOT NULL DEFAULT ''", "answer": "TEXT DEFAULT ''", "image": "TEXT DEFAULT ''", "answered_by": "TEXT DEFAULT ''", "answered_at": "TIMESTAMP"},
    }.items():
        columns = {column["name"] for column in inspector.get_columns(table_name)}
        for column_name, definition in extra_columns.items():
            if column_name not in columns:
                db.session.execute(text(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {definition}"))
    db.session.commit()


@app.teardown_appcontext
def close_db(exception=None):
    database = g.pop("db", None)
    if database is not None:
        database.close()


@app.before_request
def load_logged_in_user():
    user_id = session.get("user_id")
    g.user = None
    if user_id:
        g.user = db.session.execute(
            text("SELECT id, name, phone, email, grade, study_type, score FROM users WHERE id = :user_id"),
            {"user_id": user_id},
        ).fetchone()


def admin_required(view_func):
    @wraps(view_func)
    def wrapped_view(*args, **kwargs):
        if not current_user.is_authenticated or not isinstance(current_user, Admin):
            abort(403)
        return view_func(*args, **kwargs)
    return wrapped_view


@app.context_processor
def inject_user():
    return {"user": g.user}


@app.route("/")
def home():
    courses = Course.query.filter_by(is_active=True).order_by(Course.id.desc()).all()
    enrolled_ids = set()
    if g.user:
        enrolled_ids = {
            enrollment.course_id
            for enrollment in CourseEnrollment.query.filter_by(user_id=g.user["id"]).all()
        }
    return render_template(
        "index.html",
        courses=[course.to_card_dict() | {"subscribed": course.id in enrolled_ids} for course in courses],
    )


@app.route("/courses")
def courses():
    available_courses = Course.query.filter_by(is_active=True).order_by(Course.id.desc()).all()
    enrolled_ids = set()
    if g.user:
        enrolled_ids = {
            enrollment.course_id
            for enrollment in CourseEnrollment.query.filter_by(user_id=g.user["id"]).all()
        }
    return render_template(
        "courses.html",
        courses=[
            course.to_card_dict() | {"subscribed": course.id in enrolled_ids}
            for course in available_courses
        ],
    )


@app.route("/tools")
def tools():
    return render_template("tools.html")


@app.route("/forum", methods=["GET", "POST"])
def forum():
    if g.user is None:
        return redirect(url_for("login"))

    status_filter = request.args.get("status", "all")
    valid_filters = {"all", "open", "answered"}
    if status_filter not in valid_filters:
        status_filter = "all"

    if request.method == "POST":
        if not CourseEnrollment.query.filter_by(user_id=g.user["id"]).first():
            flash("لا يمكنك إرسال سؤال في المنتدي إلا إذا كنت مشتركًا في كورس واحد على الأقل", "error")
            return redirect(url_for("courses"))

        question = request.form.get("question", "").strip()
        if not question:
            flash("اكتب سؤالك أولاً", "error")
            return redirect(url_for("forum"))

        image_path = ""
        image_file = request.files.get("image")
        if image_file and image_file.filename:
            os.makedirs(os.path.join(app.root_path, "static", "uploads", "forum"), exist_ok=True)
            safe_name = secure_filename(image_file.filename)
            filename = f"forum_{datetime.utcnow().timestamp()}_{safe_name}"
            image_file.save(os.path.join(app.root_path, "static", "uploads", "forum", filename))
            image_path = f"/static/uploads/forum/{filename}"

        db.session.add(StudentForumQuestion(user_id=g.user["id"], question=question, image=image_path))
        db.session.commit()
        flash("تم إرسال السؤال إلى الإدارة", "success")
        return redirect(url_for("forum"))

    sql = """
        SELECT q.id, q.question, q.answer, q.image, q.created_at, q.answered_at, q.answered_by,
               u.name AS student_name, u.grade AS student_grade
        FROM student_forum_questions q
        JOIN users u ON u.id = q.user_id
    """
    params = []
    if status_filter == "open":
        sql += " WHERE q.answer IS NULL OR q.answer = ''"
    elif status_filter == "answered":
        sql += " WHERE q.answer IS NOT NULL AND q.answer != ''"
    sql += " ORDER BY q.created_at DESC"

    questions = get_db().execute(sql, params).fetchall()
    return render_template("forum.html", questions=questions, status_filter=status_filter)


@app.route("/api/verify-code", methods=["POST"])
def verify_code():
    from datetime import datetime
    from flask import jsonify
    from school_app.models import AccessCode

    if g.user is None:
        return jsonify(success=False, message="سجل دخولك الأول عشان تشترك في الكورس"), 401

    data = request.get_json(silent=True) or {}
    course_id = data.get("course_id")
    code_value = (data.get("code") or "").strip().upper()
    if not course_id or not code_value:
        return jsonify(success=False, message="من فضلك ادخل الكود"), 400

    access_code = AccessCode.query.filter_by(course_id=course_id, code=code_value).first()
    if not access_code:
        return jsonify(success=False, message="الكود غير صحيح"), 404
    if access_code.is_used:
        return jsonify(success=False, message="الكود ده مستخدم قبل كده"), 409

    if CourseEnrollment.query.filter_by(user_id=g.user["id"], course_id=course_id).first():
        return jsonify(success=True, already_subscribed=True, redirect_url=url_for("course_content", course_id=course_id))

    access_code.is_used = True
    access_code.used_at = datetime.utcnow()
    db.session.add(CourseEnrollment(user_id=g.user["id"], course_id=course_id))
    db.session.commit()
    unlocked = session.get("unlocked_courses", [])
    if int(course_id) not in unlocked:
        unlocked.append(int(course_id))
    session["unlocked_courses"] = unlocked
    return jsonify(success=True, redirect_url=url_for("course_content", course_id=course_id))


@app.route("/course/<int:course_id>/content")
def course_content(course_id):
    if g.user is None:
        return redirect(url_for("login"))
    course = Course.query.get_or_404(course_id)
    enrolled = g.user and CourseEnrollment.query.filter_by(
        user_id=g.user["id"], course_id=course_id
    ).first()
    if not enrolled:
        return redirect(url_for("home"))

    exam_report = StudentExamReport.query.filter_by(user_id=g.user["id"], course_id=course_id).first()
    response = make_response(render_template(
        "course.html",
        course=course,
        exam_report=exam_report,
        exam_score=(exam_report.score if exam_report and exam_report.result_status == "ready" else 0),
        exam_total=(exam_report.total if exam_report and exam_report.result_status == "ready" else 0),
        essay_total=sum(1 for question in course.exam_questions if question.question_type == "essay"),
        result_ready=(exam_report is not None and exam_report.result_status == "ready"),
    ))
    response.headers["Cache-Control"] = "no-store, max-age=0"
    return response


@app.route("/course-content/<int:item_id>/file")
def course_content_file(item_id):
    if g.user is None:
        return redirect(url_for("login"))

    item = ContentItem.query.get_or_404(item_id)
    enrolled = CourseEnrollment.query.filter_by(
        user_id=g.user["id"], course_id=item.course_id
    ).first()
    if not enrolled or item.content_type != "pdf":
        abort(404)

    file_name = os.path.basename(item.body.strip())
    file_path = os.path.join(app.config["CONTENT_UPLOAD_FOLDER"], file_name)
    if not os.path.isfile(file_path):
        original_name = file_name.split("_", 2)[-1]
        fallback_path = os.path.join(app.config["CONTENT_UPLOAD_FOLDER"], original_name)
        if not os.path.isfile(fallback_path):
            abort(404)
        file_path = fallback_path
    return send_file(
        file_path,
        mimetype="application/pdf",
        as_attachment=True,
        conditional=False,
        etag=False,
        max_age=0,
        download_name=f"{re.sub(r'[\\/:*?\"<>|]+', '-', item.title).strip(' .') or 'document'}.pdf",
    )


@app.route("/reports")
def reports():
    if g.user is None:
        return redirect(url_for("login"))
    reports = StudentExamReport.query.filter_by(user_id=g.user["id"]).order_by(StudentExamReport.created_at.desc()).all()
    report_rows = []
    for report in reports:
        course = Course.query.get(report.course_id)
        report_rows.append({
            "course": course,
            "report": report,
            "score_text": f"{report.score} / {report.total}",
        })
    return render_template("reports.html", report_rows=report_rows)


def get_challenge_leaders():
    results = db.session.execute(text("""
        SELECT id, name, email, study_type, score
        FROM users
        WHERE score > 0
        ORDER BY score DESC, id ASC
    """)).fetchall()

    leaders = {"center": [], "online": []}
    for row in results:
        bucket = row["study_type"]
        if bucket not in leaders:
            continue
        leaders[bucket].append({
            "id": row["id"],
            "name": row["name"],
            "email": row["email"],
            "score": row["score"],
            "study_type": row["study_type"],
        })

    return {
        "center": leaders["center"][:3],
        "online": leaders["online"][:3],
    }


@app.route("/challenges")
def challenges():
    if g.user is None:
        return redirect(url_for("login"))
    leaderboard = get_challenge_leaders()
    all_users = db.session.execute(text(
        "SELECT id, name, study_type, score FROM users ORDER BY score DESC, id ASC"
    )).fetchall()
    is_admin = current_user.is_authenticated and isinstance(current_user, Admin)
    return render_template(
        "challenges.html",
        leaderboard=leaderboard,
        all_users=all_users,
        is_admin=is_admin,
        user_score=(int(g.user["score"] or 0) if g.user else 0),
    )


@app.route("/course/<int:course_id>/exam", methods=["POST"])
def submit_exam(course_id):
    course = Course.query.get_or_404(course_id)
    if g.user is None or not CourseEnrollment.query.filter_by(
        user_id=g.user["id"], course_id=course_id
    ).first():
        return redirect(url_for("home"))

    score = 0
    objective_total = 0
    essay_total = 0
    for question in course.exam_questions:
        answer = request.form.get(f"question_{question.id}", "").strip()
        if question.question_type == "essay":
            essay_total += 1
            submission = EssaySubmission.query.filter_by(user_id=g.user["id"], course_id=course_id, question_id=question.id).first()
            if submission is None:
                submission = EssaySubmission(user_id=g.user["id"], course_id=course_id, question_id=question.id)
                db.session.add(submission)
            submission.answer = answer
            submission.score = 0
            submission.feedback = ""
            submission.status = "pending"
            submission.updated_at = datetime.utcnow()
            db.session.commit()
        else:
            objective_total += question.marks
            if answer == question.correct_option:
                score += question.marks

    report = StudentExamReport.query.filter_by(user_id=g.user["id"], course_id=course_id).first()
    if report is None:
        report = StudentExamReport(user_id=g.user["id"], course_id=course_id)
        db.session.add(report)
    report.score = score
    report.total = objective_total
    report.result_status = "ready" if essay_total == 0 else "pending"
    report.review_summary = "تم التصحيح" if essay_total == 0 else "قيد التصحيح"
    report.achievements = report.achievements or ""
    report.weak_points = report.weak_points or ""
    report.admin_analysis = report.admin_analysis or ""
    db.session.commit()

    return redirect(url_for("course_content", course_id=course_id))


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        phone = request.form.get("phone", "").strip()
        guardian_phone = request.form.get("guardian_phone", "").strip()
        email = request.form.get("email", "").strip().lower()
        grade = request.form.get("grade", "").strip()
        study_type = request.form.get("study_type", "").strip()
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if password != confirm_password:
            return render_template("register.html", error="كلمتا المرور غير متطابقتين"), 400

        try:
            if db.engine.dialect.name == "postgresql":
                result = db.session.execute(text("""
                    INSERT INTO users (name, phone, guardian_phone, email, grade, study_type, password)
                    VALUES (:name, :phone, :guardian_phone, :email, :grade, :study_type, :password)
                    RETURNING id
                """), {
                    "name": name,
                    "phone": phone,
                    "guardian_phone": guardian_phone,
                    "email": email,
                    "grade": grade,
                    "study_type": study_type,
                    "password": generate_password_hash(password),
                })
                db.session.commit()
                user_id = result.scalar_one()
            else:
                db.session.execute(text("""
                    INSERT INTO users (name, phone, guardian_phone, email, grade, study_type, password)
                    VALUES (:name, :phone, :guardian_phone, :email, :grade, :study_type, :password)
                """), {
                    "name": name,
                    "phone": phone,
                    "guardian_phone": guardian_phone,
                    "email": email,
                    "grade": grade,
                    "study_type": study_type,
                    "password": generate_password_hash(password),
                })
                db.session.commit()
                user_id = db.session.execute(text("SELECT last_insert_rowid() AS id")).scalar()
        except Exception:
            return render_template("register.html", error="البريد الإلكتروني مستخدم بالفعل"), 409

        session.clear()
        session["user_id"] = user_id
        return redirect(url_for("home"))

    return render_template("register.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        user = db.session.execute(
            text("SELECT * FROM users WHERE email = :email"),
            {"email": email},
        ).fetchone()

        if user is None or not check_password_hash(user["password"], password):
            return render_template("login.html", error="البريد الإلكتروني أو كلمة المرور غير صحيحة"), 401

        session.clear()
        session["user_id"] = user["id"]
        return redirect(url_for("home"))

    return render_template("login.html")


def send_reset_email(email, token):
    mail_server = os.environ.get("MAIL_SERVER")
    mail_port = int(os.environ.get("MAIL_PORT", "587"))
    mail_username = os.environ.get("MAIL_USERNAME")
    mail_password = os.environ.get("MAIL_PASSWORD")
    mail_sender = os.environ.get("MAIL_SENDER", mail_username or "noreply@example.com")

    if not mail_server or not mail_username or not mail_password:
        return False, token

    reset_url = url_for("reset_password", token=token, _external=True)
    message = EmailMessage()
    message["Subject"] = "إعادة تعيين كلمة المرور"
    message["From"] = mail_sender
    message["To"] = email
    message.set_content(
        f"عزيزي الطالب،\n\n"
        f"تم إنشاء رابط لإعادة تعيين كلمة المرور الخاص بك.\n"
        f"الرابط: {reset_url}\n\n"
        "إذا لم تطلب هذا التغيير، يمكنك تجاهل الرسالة."
    )

    try:
        with smtplib.SMTP(mail_server, mail_port) as smtp:
            smtp.starttls()
            smtp.login(mail_username, mail_password)
            smtp.send_message(message)
        return True, reset_url
    except Exception:
        return False, reset_url


@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        user = db.session.execute(
            text("SELECT * FROM users WHERE email = :email"),
            {"email": email},
        ).fetchone()

        if user is not None:
            token = secrets.token_urlsafe(24)
            expires_at = datetime.utcnow() + timedelta(minutes=30)
            db.session.execute(
                text("UPDATE users SET reset_token = :token, reset_token_expires_at = :expires_at WHERE id = :user_id"),
                {"token": token, "expires_at": expires_at.strftime("%Y-%m-%d %H:%M:%S"), "user_id": user["id"]},
            )
            db.session.commit()

            sent, detail = send_reset_email(email, token)
            if sent:
                return render_template("forgot_password.html", success="تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني.")
            return render_template("forgot_password.html", success="تم إنشاء رابط استعادة كلمة المرور. استخدم هذا الرابط في الاختبار المحلي:", reset_link=detail)

        return render_template(
            "forgot_password.html",
            success="إذا كان البريد مسجلًا، سيتم إرسال رابط استعادة كلمة المرور إليه.",
        )

    return render_template("forgot_password.html")


@app.route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    user = db.session.execute(
        text("SELECT * FROM users WHERE reset_token = :token"),
        {"token": token},
    ).fetchone()

    if user is None:
        return render_template("reset_password.html", valid=False, message="رابط إعادة التعيين غير صالح أو منتهي.")

    expires_at = user["reset_token_expires_at"]
    try:
        if expires_at and datetime.strptime(expires_at, "%Y-%m-%d %H:%M:%S") < datetime.utcnow():
            return render_template("reset_password.html", valid=False, message="انتهت صلاحية رابط إعادة التعيين.")
    except (TypeError, ValueError):
        return render_template("reset_password.html", valid=False, message="رابط إعادة التعيين غير صالح.")

    if request.method == "POST":
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if len(password) < 6:
            return render_template("reset_password.html", valid=True, token=token, error="كلمة المرور يجب أن تكون 6 أحرف على الأقل.")
        if password != confirm_password:
            return render_template("reset_password.html", valid=True, token=token, error="كلمتا المرور غير متطابقتين.")

        db.session.execute(
            text("UPDATE users SET password = :password, reset_token = '', reset_token_expires_at = NULL WHERE id = :user_id"),
            {"password": generate_password_hash(password), "user_id": user["id"]},
        )
        db.session.commit()
        return redirect(url_for("login"))

    return render_template("reset_password.html", valid=True, token=token)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.route("/dashboard")
def dashboard():
    if g.user is None:
        return redirect(url_for("login"))
    enrollments = CourseEnrollment.query.filter_by(user_id=g.user["id"]).order_by(
        CourseEnrollment.created_at.desc()
    ).all()
    return render_template("dashboard.html", enrollments=enrollments)


with app.app_context():
    init_db()
    db.create_all()
    exam_columns = {
        column[1] for column in db.session.execute(db.text("PRAGMA table_info(exam_questions)"))
    }
    if "question_type" not in exam_columns:
        db.session.execute(db.text(
            "ALTER TABLE exam_questions ADD COLUMN question_type VARCHAR(20) NOT NULL DEFAULT 'mcq'"
        ))
        db.session.commit()
    if "marks" not in exam_columns:
        db.session.execute(db.text(
            "ALTER TABLE exam_questions ADD COLUMN marks INTEGER NOT NULL DEFAULT 1"
        ))
        db.session.commit()
    if not Admin.query.first():
        default_admin = Admin(username="admin")
        default_admin.set_password("admin123")
        db.session.add(default_admin)
        db.session.commit()


if __name__ == "__main__":
    app.run(debug=True)